### ISSUE TITLE
Rebase all branches

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/covid-moonshot-ml#26]
With the forced changes in the repo's history, we need to check and rebase all the branches on top of `main`, such that the history makes sense when we try to merge them into `main`. Following instructions from https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#fully-removing-the-data-from-github 

# ToDos
- [x] Delete all the branches that are not going to be even considered (@apayne97 @kaminow )
- [ ] Rebase with the help of magic tools (PyCharm, bash, kompare, etc.) (@kaminow @ijpulidos )

# Branches list

Please check the ones that have been already _rebased_ or don't need _rebasing_. Or remove the ones that don't apply (check first item in ToDos list)

- [x] remotes/origin/HEAD -> origin/main
- [x] remotes/origin/add-data-downloading
- [x] remotes/origin/add-loss-functions
- [x] remotes/origin/add-uncertainties
- [x] remotes/origin/dataset-allow-duplicates
- [x] remotes/origin/fix-docking
- [x] remotes/origin/fix-qm9-discrete-energies
- [ ] remotes/origin/graph-nets
- [x] remotes/origin/hallucinate-fragalysis
- [x] remotes/origin/improve-documentation
- [x] remotes/origin/main
- [x] remotes/origin/major-restructure
- [x] remotes/origin/mers-docking
- [x] remotes/origin/update-kinoml

**Comment by ijpulidos** [comment]
I think ideally we want to do this before merging any other PRs, so this is somewhat urgent. Just to avoid changing `main` along the way and not having a single point for the rebase.

**Comment by ijpulidos** [comment]
Basically what we are doing here so far is rebasing each branch as instructed, with `git rebase main <branch>` (while standing on the branch). And after resolving all the merge conflicts (with the help of PyCharm), we compare the resulting branch with an snapshot of the repo that was taken right before its history was changed/broken (in the same branch). We do this by running
```bash
for file in `find . -name '*.py'`; do diff -q ${file} ../covid-moonshot-before-oelicense-fix/${file} || kompare ${file} ../covid-moonshot-before-oelicense-fix/${file} ; done
```
where `covid-moonshot-before-oelicense-fix` is where the previous snapshot of the repo lives.

**Comment by apayne97** [comment]
Thanks, @ijpulidos, we have needed this. I don't fully understand the implications of what you're doing but just to make it a bit simpler for you, I deleted these branches, after confirming that all commits have (prevously) been merged into hallucinate-fragalysis:
[] improve-documentation
[] mers-docking
[] update-kinoml
[] fix-docking

**Comment by apayne97** [comment]
I don't know where these branches are (they were before me), they aren't on github so they may have been previously deleted:
- [ ] remotes/origin/add-data-downloading
- [ ] remotes/origin/dataset-allow-duplicates
Maybe @kaminow can confirm that these can be checked off.

**Comment by apayne97** [comment]
@kaminow @ijpulidos can we finish this today?

**Comment by ijpulidos** [comment]
I forgot to ask @kaminow in our meeting if he needed some help with rebasing and checking the last two branches that are missing. Please let me know!

**Comment by kaminow** [comment]
I'll probably want to do the last one (`hallucinate-fragalysis`) with you, but I'm currently working on adding the dimers in a separate branch (`add-dimer`). I think it might make sense to wait until I've pulled this one back into `hallucinate-fragalysis` before we do the rebasing just so we don't have to do it to both branches

**Comment by ijpulidos** [comment]
That  works, let me know!

**Comment by mikemhenry** [comment]
We can use this PR to track progress on rebasing `hallucinate-fragalysis` https://github.com/choderalab/covid-moonshot-ml/pull/39
