### ISSUE TITLE
Create MERS fauxalysis dataset

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#29]
# Task Overview
- [ ] Download and align MERS structures from the PDB
- [ ] Create design units for every MERS structure (`Structure_Source`) and fragalysis compound (`Compound_ID`)
- [ ] Run docking 
- [ ] Analyze docking results
- [ ] Pick 1 best structure for each `Compound_ID` and provide a Fragalysis-like directory to hand off to medicinal chemists

**Comment by apayne97** [comment]
We're currently in a design-make-test cycle for docking, analyzing, and picking the best structures but we have most of the code set up to do this!
