### ISSUE TITLE
Which structure should we pick for MERS-Fauxalysis dataset?

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#31]
# To-Do
- [x] pick one of the methods / implementations below and use to generate a dataset

### 1) Lowest RMSD; then lowest Chemgauss4 score
- [x] implemented here by @kaminow : https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/scripts/hallucinate_fragalysis.py#L86
- [x] implemented here by @apayne97 : https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/covid_moonshot_ml/docking/analysis.py#L198

### 2) Filter by "good" scores first, then pick the best one (could try with different sets of scores
- [x] discussed here: #32 
- [x] implement in `DockingResults` class

**Comment by apayne97** [comment]
The current plan is just to filter by `RMSD < 2.5` and then sort by `POSIT`, `Chemgauss4`, and then by `RMSD`.

**Comment by apayne97** [comment]
added in this commit: https://github.com/choderalab/covid-moonshot-ml/commit/cde58850d9bf90e91004acda79d9bd857ecaaa16
```
    def get_best_structure_per_compound(self,
                                        filter_score="RMSD",
                                        filter_value=2.5,
                                        score_order=['POSIT_R', 'Chemgauss4', 'RMSD']):
        """
        Gets the best structure by first filtering based on the filter_score and filter_value,
        then sorts in order of the scores listed in score_order.

        As with everything else, lower scores are assumed to be better, requiring a conversion of some scores.

        Parameters
        ----------
        filter_score
        filter_value
        score_order

        Returns
        -------

        """

        filtered_df = self.df[self.df[filter_score] < filter_value]
        sort_list = ['Compound_ID'] + score_order
        sorted_df = filtered_df.sort_values(sort_list, ascending=[True, True, True, True])
        g = sorted_df.groupby('Compound_ID')
        self.best_df = g.head(1)
        return self.best_df
```

**Comment by apayne97** [comment]
@kaminow I should have done this in a pull request but I didn't want to slow things down by making a new branch. but the syntax for sorting by multiple columns with pandas is actually pretty simple!
