### ISSUE TITLE
Catalogue and fix issues with docking protocol

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#36]
# To-Do
- [x] catalogue all the DUs that ended up with the ligand outside the binding site
- [x] identify potential solutions
- [x] add solutions

# List of unresolved issues:
- [x] docked molecules nearly clash with MERS structures (?) not sure if its close enough to be a problem
  - [x] need to upload the documented issue here

**Comment by apayne97** [comment]
I didn't know where to put this, so I guess it goes here:
![image](https://user-images.githubusercontent.com/31800806/190167280-c4c20bf2-70bc-428f-8f66-6725094d0656.png)

compressed pymol session with relevant compounds:
[ANN-UNI_analysis.pse.zip](https://github.com/choderalab/covid-moonshot-ml/files/9566737/ANN-UNI_analysis.pse.zip)

the Chemgauss4 score is better (4YLU and 5C3N) for the structures which have a protonated active site histidine
the RMSD is way worse for 4YLU bc the ligand is flipped around
