### ISSUE TITLE
Visualize and scriptify docking results from analysis

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#40]
# To-Do
- [x] play around in jupyter notebook
- [x] turn into functions
- [x] put into a script

**Comment by apayne97** [comment]
Put into a script here: https://github.com/choderalab/covid-moonshot-ml/commit/2c7a0121532d2a4e5a5a992bb18a9ccaa0b95368
