### ISSUE TITLE
Save sufficient conda environments with intelligent names

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#41]
# To-Do
### Conclusion: Use this version to save docking envs
`conda env export --no-builds`

### 1. This one is in a nice format for figuring out exactly where the packages are from (although I guess its a csv, not a yaml file) 
- https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/devtools/conda-envs/mers-docking-clean.yaml
```
# packages in environment at /Users/alexpayne/opt/anaconda3/envs/mers-docking:
#
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
abseil-cpp                20211102.0           h96cf925_1    conda-forge
absl-py                   1.1.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1            py39h63b48b0_1    conda-forge
...
```
- [ ] change file extension

### 2. This one is much easier to read and is the most minimal
- https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/devtools/conda-envs/mers-docking2.yaml
- `conda env export --from-history > mers-docking2.yaml`
```
name: mers-docking2
channels:
  - schrodinger
  - salilab
  - openeye
  - conda-forge
  - http://conda.anaconda.org/omnia
  - defaults
dependencies:
  - biopython
  - pydantic
  - python=3.8
  - pandas
  - pymol
  - pyyaml
...
```
### 3. This one also includes the pip dependencies and is the most complete
- https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/devtools/conda-envs/mers-docking2_complete.yaml
- `conda env export > mers-docking2_complete.yaml`
```
name: mers-docking2
channels:
  - anaconda
  - schrodinger
  - salilab
  - openeye
  - conda-forge
  - http://conda.anaconda.org/omnia
  - defaults
dependencies:
  - ambertools=22.0=py38hd6424c8_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38hed1de0f_2
  - arpack=3.7.0=hefb7bc6_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
...
- pip:
    - amberlite==22.0
    - amberutils==21.0
    - kaleido==0.2.1
    - kinoml==0+unknown
    - mmpbsa-py==16.0
    - packmol-memgen==1.2.3rc0
 ...
```

## Split by operating system (is this necessary?)
- [ ] MacOS (M1 vs other?)
- [ ] Linux

## remove old ones
- [ ]  https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/devtools/conda-envs/mers-docking.yaml

**Comment by mikemhenry** [comment]
What is our goal with these? `conda list --explicit` works pretty well to recreate an environment, but it isn't portable across architectures, since it gives the full URL path to the packages.

**Comment by apayne97** [comment]
I guess there are two goals.
1) for us (as users of the repo) to be able to recreate the environments between wherever we're trying to run things (for me, at least locally on my laptop as well as on lilac)
2) for you (as testers/maintainers) to be able to run whatever unit tests we will add and check that all the code still runs

**Comment by mikemhenry** [comment]
> least locally on my laptop as well as on lilac

Then we probably want a format without the build strings, so `conda env export --no-builds` seems to be the right compromise between reproducible, but also portable.

**Comment by kaminow** [comment]
> `conda env export --no-builds`
I'm pretty sure this is what I used to generate the `test` env in the `moonshot_ml.yaml` file
