### ISSUE TITLE
Re-write hallucinate_fragalysis as a more flexible API

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#46]
# Intro
Currently the main `hallucinate_fragalysis.py` script includes a combination of hard-coded settings, pulling from the `covid_moonshot_ml` api, and self-contained functions. 

The goal is to section off parts of the code into functions within the API and to have a much simpler script that pulls from the API.

# Steps to Separate Out
|Goal | Inputs | Outputs | Moved (Y/N) | New Code Location | 
|-|-|-|-|-|
| 1. Downloading PDB files | list of PDBs | directory of downloaded PDBs | N | |
| 2. Re-build side chains, missing loops |  directory of downloaded PDBs, re-building options | directory of re-built PDBs | N | |
| 3. Aligning PDB files to a reference | path to reference, directory of re-built PDBs | directory of aligned PDBs | N | |
| 4. Build design units | path to aligned PDB, path to fragalysis structure | `Compound_ID_Structure_Source`.oedu, `Compound_ID_Structure_Source`_seqres.pdb, `Compound_ID_Structure_Source`_predocked.sdf | N | |
| 5. Run docking | path to design unit | `Compound_ID_Structure_Source`_bound.pdb, `Compound_ID_Structure_Source`_docked.sdf | N | |
| 6. Calculate RMSD |  predocked `OEMol`, docked `OEMol` | RMSD (float) | N | |
| 7. Pull all scores from results | path to `*_docked.sdf` OR OE objects | scores | N | |
| 8. Write CSV of docking results | `Complex_ID`, `Compound_ID`, `Structure_Source`, `Output_Dir`, and any scores | all_results.csv | N | |
| 9. Analyze results | path to `all_results.csv` | `all_results_cleaned.csv`, `by_compound.csv`, `by_structure.csv`, `mers_fauxalysis.csv` | Y | `scripts/clean_results_csv.py` |
| 10. Generate "fauxalysis" directory | path to docking results, path to `mers_fauxalysis.csv` | fauxalysis directory | Y* | `scripts/fauxalysis_from_docking.py` | 
| 11. Plot docking results | path to outputs from `9.`| a bunch of plots! | Y | `scripts/plot_docking_results.py` |

*10 is also in hallucinate fragalysis but they have very different implementations: https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/scripts/hallucinate_fragalysis.py#L54

## The current plan is to have these as individual scripts:
Step 1-3
Step 4-8 (with options to run only some of the steps)
Step 9
Step 10
Step 11

# To-Do
Make these scripts
- [x] `prep_proteins.py` (Steps 1-3)
- [x] `mers_docking.py` (Steps 4-8, probably just rename `hallucinate_fragalysis.py`
- [x] `clean_results_csv.py` (Step 9)
- [x]  `fauxalysis_from_docking.py` (Step 10)
- [x] `plot_docking_results.py` (Step 11)
