### ISSUE TITLE
add pymol scripts to repo

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#77]
# Description
It would be nice to at least somewhat automate the process of generating nice docking visuals from our results. Hopefully wee can write everything in a way that would make it potentially reusable between different sub-projects.

# TODO
- [ ] decide what we want to be able to visualize
- [ ] decide if it's worth making progress on this or if we should wait to be able to upload this to Fragalysis instead

## What our resulting scripts should have
- [ ] common viewing angle for active site

**Comment by apayne97** [comment]
did a good rough draft of this in #83
