### ISSUE TITLE
Improve Analysis and Visualization of Docking Results

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#79]
# To-Do
## Analysis Improvement
- [ ] normalize the "counting" scores from 0 to 1 where 1 is the largest possible number (not necessarily the largest number seen)

## Bonus Features
- [ ] deploy dash app for collaborators to view

# Relevant PRs
- [ ] #59 incomplete - left a lot of things to do
